#!/bin/bash

set -e

## For debugging
# set -x
# trap read debug

CWD=$PWD
#cd $(dirname $(readlink -f "$0"))/..

function usage() {
  >&2 echo "Usage: $0 [ --post [ --rust ] ]"
  >&2 echo "       where --post deploys to personal CRAN-like repository."
  >&2 echo "             --rust if the deployment involves static libraries."
  exit 1
}

OPTS=""
while [[ $# -gt 0 ]]
do
  if [[ "$1" == --rust ]]
  then
    if [[ -z "$FLAG_POST" ]]
    then
      >&2 echo "The '--rust' flag is only available when using the '--post' flag."
      usage
    fi
    OPTS="--rust"
    shift
  elif [[ "$1" == --post ]]
  then
    FLAG_POST=true
    shift
  else
    usage
  fi
done

if [[ $# -ne 0 ]]
then
  usage
fi

if [[ $(find . -name DESCRIPTION | wc -l) -ne 1 ]]
then
  >&2 echo "Cannot find the unique DESCRIPTION file."
  >&2 echo 
  >&2 find . -name DESCRIPTION 
  exit 2
fi

PKG_BASE=$(basename $(dirname $(find . -name DESCRIPTION)))

trim() {
    local var="$*"
    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"   
    echo -n "$var"
}

cd $PKG_BASE
PKG_NAME=$(trim $(grep '^Package: ' DESCRIPTION | sed -e 's/^Package: //g'))
PKG_VERSION=$(trim $(grep '^Version: ' DESCRIPTION | sed -e 's/^Version: //g'))
cd ..

if [[ ! -e ${PKG_NAME}/NAMESPACE ]]
then
  touch ${PKG_NAME}/NAMESPACE
fi

R CMD INSTALL $PKG_NAME

cd $PKG_NAME
R --slave -e 'devtools::document()'
cd ..

R CMD build $PKG_NAME

TGZ_NAME=${PKG_NAME}_${PKG_VERSION}.tar.gz

mkdir -p deliveries
mv $TGZ_NAME deliveries

if [[ "$FLAG_POST" ]]
then
  deploy-R-package $OPTS "deliveries/$TGZ_NAME"
fi

